import type { Metadata } from "next";
import "./globals.css";
import style from "./layout.module.css";
import Link from "next/link";
import localFont from "next/font/local";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <div className={style.container}>
          <header className={style.header}>
            <Link href="/">ONEBITE CINEMA</Link>
          </header>
          <main className={style.main}>
            <div>{children}</div>
          </main>
          <footer className={style.footer}>@lulullu</footer>
        </div>
        {modal}
        <div id="modalRoot"></div>
      </body>
    </html>
  );
}
